import Head from "next/head"
import styles from "@/styles/Index.module.css"
import { useEffect } from "react"
import ContactForm from "@/components/ContactForm"

export default function Home() {
	useEffect(() => {
		const appHeight = () => {
			const doc = document.documentElement
			doc.style.setProperty("--app-height", `${window.innerHeight}px`)
		}
		window.addEventListener("resize", appHeight)
		appHeight()
		return () => window.removeEventListener("resize", appHeight)
	}, [])
	return (
		<>
			<Head>
				<title>Matt Murphy</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>Matthew Daniel Murphy</h1>
				<div className={styles.container}>
					<p className={styles.paragraph}>projects</p>
					<h2 className={styles.heading}>
						<a className={styles.link} href='/blocks' text='Blockdoku'>
							Blockdoku
						</a>
					</h2>
					<h2 className={styles.heading}>
						<a className={styles.link} href='https://typery.mattmurphy.ca' text='Typery'>
							Typery (abandoned)
						</a>
					</h2>
				</div>
				<div className={styles.container}>
					<p className={styles.paragraph}>social media</p>
					<h2 className={styles.heading}>
						<a className={styles.link} href='https://www.instagram.com/matthewdanielmurphy' text='Instagram'>
							Instagram
						</a>
					</h2>
				</div>
				<div className={styles.container}>
					<p className={styles.paragraph}>Contact</p>
					<ContactForm />
				</div>
			</main>
		</>
	)
}
