import Head from 'next/head'
import { useEffect } from 'react'

export default function Home() {
	useEffect(() => {
		const appHeight = () => {
			const doc = document.documentElement
			doc.style.setProperty(' — app-height', `${window.innerHeight}px`)
		}
		window.addEventListener('resize', appHeight)
		appHeight()
		return () => window.removeEventListener('resize', appHeight)
	}, [])
	return (
		<>
			<Head>
				<title>Matt Murphy</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1>Matthew Daniel Murphy</h1>
				<div>
					<p>social media</p>
					<h2>
						<a
							href='https://www.instagram.com/matthewdanielmurphy'
							class='glitch-hover'
							text='Instagram'
						>
							Instagram
						</a>
					</h2>
				</div>
				<div>
					<p>projects</p>
					<h2>
						<a
							href='https://typery.mattmurphy.ca'
							class='glitch-hover'
							text='Typery'
						>
							Typery
						</a>
					</h2>
				</div>
			</main>
		</>
	)
}
