import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Matt Murphy</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<div>
					<p>name</p>
					<h2>Matthew Daniel Murphy</h2>
				</div>
				<div>
					<p>social media</p>
					<h2>
						<a href='https://www.instagram.com/matthewdanielmurphy'>
							Instagram
						</a>
					</h2>
				</div>
				<div>
					<p>projects</p>
					<h2>
						<a href='https://typery.mattmurphy.ca'>Typery</a>
					</h2>
				</div>
			</main>
		</>
	)
}
