import Head from 'next/head'
import Image from 'next/image'
import { Atkinson_Hyperlegible } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const atkinson = Atkinson_Hyperlegible({
	subsets: ['latin'],
	variable: '--atkinson',
	weight: ['700', '400'],
})

export default function Home() {
	return (
		<>
			<Head>
				<title>Matt Murphy</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.container}>
				<main className={styles.main}>
					<h1 className={styles.h1}>
						👋 &nbsp; I&apos;m{' '}
						<span className={styles.name}>Matthew Daniel Murphy</span>.
					</h1>
					<ul className={styles.list}>
						<li>
							I&apos;m a <strong>developer</strong>.
						</li>
						<li>
							I&apos;m a <strong>musician</strong>.
						</li>
						<li>
							I&apos;m a <strong>lot of other things</strong>.
						</li>
					</ul>
					<p className={styles.buttons}>
						<a
							className={styles.linkButton}
							href='https://www.instagram.com/matthewdanielmurphy'
						>
							Instagram
						</a>
					</p>
				</main>
			</div>
		</>
	)
}
