import { Atkinson_Hyperlegible } from '@next/font/google'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
const atkinson = Atkinson_Hyperlegible({
	weight: ['400', '700'],
	subsets: ['latin'],
})

export default function Home() {
	return (
		<>
			<Head>
				<title>Matt Murphy</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<style jsx global>{`
					html {
						font-family: ${atkinson.style.fontFamily};
					}
				`}</style>
			</Head>
			<div className={atkinson.className}>
				<div className={styles.container}>
					<main className={styles.main}>
						<h1 className={styles.h1}>
							Matt <span>Daniel</span> Murphy
						</h1>
						<ul className={styles.list}>
							<li className={styles.developer}>developer</li>
							<li className={styles.musician}>musician</li>
							<li className={styles.etc}>et cetera</li>
						</ul>
						<p className={styles.buttons}>
							<a
								className={styles.linkButton}
								href='https://www.instagram.com/matthewdanielmurphy'
							>
								my instagram
							</a>
						</p>
					</main>
				</div>
			</div>
		</>
	)
}
