name: Scheduled Email Cron

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Log start time
        run: echo "Job started at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

      - name: Trigger email cron endpoint
        run: |
          response=$(curl -s -w "\n%{http_code}" -X GET \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          "${{ secrets.VERCEL_URL }}/api/cron/send-scheduled-emails")

          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "Response: $body"
          echo "Status code: $status_code"

          if [ "$status_code" -ne 200 ]; then
            echo "Error: Request failed with status $status_code"
            exit 1
          fi

      - name: Log end time
        if: always()
        run: echo "Job ended at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
